### ISSUE TITLE
To Do: Documenting how to setup the local infrastructure

### ISSUE THREAD

**Issue by notand** [dataramblers/hackathon17#1]
Liebe Leute, besonders @sschuepbach und @guenterh,

danke euch für die viele Vorbereitungsarbeit!

Habt ihr schon einen Plan, wie man (also z.B. ich) die nötige Infrastruktur lokal auf meinem Rechner (Ubuntu) aufsetzen soll? Docker installieren und dann die Docker-Repos benutzen? Bei Zeppelin: Welches von beiden? Bestimmte Installationsreihenfolge? Voraussetzungen? ...?
Iich habe mich durch die Repositorien und commits gelesen, insbesondere die READMEs, die Hackathon-Infrastruktur.mm und die hints.md, und das Wiki. Bin aber nicht sicher wo anfangen.
Wir können uns auch gerne treffen, jemand erklärts mir, und ich dokumentiere es dann hier für alle anderen...

Danke!
LG - Andrea

**Comment by sschuepbach** [comment]
Liebe @notand 

Ich bin leider noch nicht dazu gekommen, eine ausführliche Installationsanleitung zu schreiben. Ev. müssten wir diesen Task auf den Hackathon verschieben. ;-)
Für die Zeit bis dahin einige Hinweise:
- Voraussetzung für die Installation ist eine möglichst aktuelle Version von Docker (am besten 17.06) und von [Docker Compose](https://docs.docker.com/compose/). Da in den Paketquellen vieler (Linux-)Distributionen Docker nicht in der aktuellsten Version und Docker Compose überhaupt nicht vorhanden ist, musst du wahrscheinlich beide Applikationen von Hand installieren. Eine Anleitung dazu findest du auf den entsprechenden Websites.
- Klone anschliessend das hackathon17-Repository: `git clone git@github.com:dataramblers/hackathon17.git` und wechsle ins Verzeichnis
- Damit Elasticsearch funktioniert, wird genügen virtueller Arbeitsspeicher benötigt. Eine [Anleitung](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) dazu findest du auf der Website von Elasticsearch.
- Danach solle alles mit einem einfachen `docker-compose up` funktionieren (das Programm lädt die entsprechenden Docker-Images herunter und initialisiert die Container). Der Elasticsearch-Cluster ist über `localhost:9200`, die Zeppelin-Instanz über `localhost:8080`, das Dashboard des Flink-Clusters über `localhost:8081` verfügbar.

Lass es mich wissen, falls etwas nicht klappt!

**Comment by notand** [comment]
Danke, bei mir hats so funktioniert. :+1:  Ich habe die Infos ins readme.md übertragen, nach bestem Wissen und Gewissen. Bitte gerne gegenchecken und korrigieren...

**Comment by notand** [comment]
@sschuepbach Danke fürs Gegenchecken und Überarbeiten im readme.md, Sebastian!
